# Generated by Django 2.2.3 on 2019-07-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('empno', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('mgr', models.CharField(max_length=200)),
                ('hiredate', models.DateTimeField(verbose_name='date published')),
                ('sal', models.IntegerField()),
                ('commisions', models.IntegerField()),
                ('deptno', models.IntegerField()),
                ('dname', models.CharField(max_length=100)),
                ('loc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'employee_details',
                'managed': False,
            },
        ),
    ]
