# Generated by Django 2.2.3 on 2019-07-14 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_det', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employeedetails',
            table='employee_detail',
        ),
    ]
